services: # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: demo2-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - demo2-network
    mem_limit: 2g
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Password123 -C -Q 'SELECT 1'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # .NET API Application
  demo2-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo2-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=demo;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=true;
    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - demo2-network
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local

networks:
  demo2-network:
    driver: bridge
